language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wmicallef/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wmicallef/docker-react npm run test